project:
  type: website
  output-dir: docs

website:
  title: "Fintech 533 Breakout Strategy"
  navbar:
    left:
      - href: index.qmd
        text: Breakout Report
      - href: about.qmd
        text: Methodology

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full
